all:
  hosts:
    lima-pwnpad:
      ansible_ssh_common_args: "-F {{ lookup('env', 'HOME') }}/.lima/pwnpad/ssh.config"
    lima-pwnpad-builder:
      ansible_ssh_common_args: "-F {{ lookup('env', 'HOME') }}/.lima/pwnpad-builder/ssh.config"
