---
- name: Resize /dev/vda2 partition
  hosts: lima-pwnpad-builder
  gather_facts: false
  become: true
  tasks:
    - name: Install growpart
      ansible.builtin.pacman:
        name: cloud-guest-utils
        state: present

    - name: Get disk and partition info
      ansible.builtin.shell: |
        DISK="/dev/vda"
        PARTITION="/dev/vda2"
        DISK_SIZE_BYTES=$(lsblk -bno SIZE ${DISK})
        PARTITION_SIZE_BYTES=$(lsblk -bno SIZE ${PARTITION})
        echo "DISK_SIZE_BYTES=${DISK_SIZE_BYTES}"
        echo "PARTITION_SIZE_BYTES=${PARTITION_SIZE_BYTES}"
      register: disk_info
      changed_when: false

    - name: Parse disk and partition info
      ansible.builtin.set_fact:
        disk_size_bytes: "{{ disk_info.stdout | regex_search('DISK_SIZE_BYTES=(\\d+)', '\\1') | first }}"
        partition_size_bytes: "{{ disk_info.stdout | regex_search('PARTITION_SIZE_BYTES=(\\d+)', '\\1') | first }}"

    - name: Calculate free space
      ansible.builtin.set_fact:
        free_space_bytes: "{{ (disk_size_bytes | int) - (partition_size_bytes | int) }}"

    - name: Print disk and partition info (debug)
      ansible.builtin.debug:
        msg: "Disk Size: {{ disk_size_bytes | int / (1024*1024*1024) }} GB, Partition Size: {{ partition_size_bytes | int / (1024*1024*1024) }} GB, Free Space: {{ free_space_bytes | int / (1024*1024*1024) }} GB"

    - name: Check if resize is needed
      ansible.builtin.set_fact:
        resize_needed: "{{ (free_space_bytes | int) > (100 * 1024 * 1024) }}"

    - name: Resize partition /dev/vda2 to fill remaining space using growpart
      ansible.builtin.shell: |
        growpart /dev/vda 2
      when: resize_needed | bool
      changed_when: true

    - name: Delete growpart
      ansible.builtin.pacman:
        name: cloud-guest-utils
        state: present
